/**
 * @file encryption.ts
 * @package @internal/plugin-agent-backend (platform/compliance)
 *
 * @description
 * Field-level cryptographic service responsible for the protection of data at rest.
 * Provides structural encryption and decryption primitives used to isolate and mask
 * Protected Health Information (PHI) and Personally Identifiable Information (PII) before
 * data is synchronized to downstream vector repositories (like Mem0/pgvector) or exposed
 * to external multi-tenant infrastructure.
 *
 * @runtime_context
 * Stateless platform utility. Executed synchronously inside HTTP mutation pathways or
 * within non-deterministic Temporal Activities preceding external network storage operations.
 *
 * @compliance_and_security
 * - HIPAA / SOC-2: Implements authenticated encryption models to protect health keys, identities,
 *   and sensitive text fields, verifying that decrypted data never touches long-term storage logs.
 * - FINRA: Integrates securely with outbound Key Vault drivers to rotate keys and enforce precise
 *   access control boundaries over cryptographic operations.
 *
 * @example
 * ```ts
 *    // Initializing with an enterprise key fetched securely from your key-vault driver plugin
 *    const secureHexKey = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
 *    const cryptoService = new FieldEncryptionService(secureHexKey);

 *    // Guarding sensitive patient records prior to vector store indexing
 *    const rawMedicalSummary = 'Patient exhibits symptoms of acute sleep apnea. Prescribed 10mg Ambien.';
 *    const secureSummary = cryptoService.encryptField(rawMedicalSummary);

 *    console.log(secureSummary);
 *    // Output: "a1b2c3...:d4e5f6...:789abc..." (Safe for external vector store lookup syncing)

 *    // Recovering context parameters inside an activity task loop
 *    const decryptedSummary = cryptoService.decryptField(secureSummary);
 *    console.log(decryptedSummary === rawMedicalSummary); // true
 * ```
 */

import * as crypto from 'crypto';

interface EncryptionConfig {
  algorithm: string;
  keyLength: number;
}

export class FieldEncryptionService {
  private readonly config: EncryptionConfig;
  private readonly masterKey: Buffer;

  /**
   * Initializes the encryption service.
   * @param rawSecretKey - A hex-encoded secure string or buffer retrieved from an authorized Key Vault driver.
   */
  constructor(rawSecretKey: string) {
    this.config = {
      algorithm: 'aes-256-gcm', // Highly resilient authenticated encryption standard
      keyLength: 32, // Requisite bit depth for AES-256
    };

    this.masterKey = Buffer.from(rawSecretKey, 'hex');
    if (this.masterKey.length !== this.config.keyLength) {
      throw new Error(`Compliance Cryptographic Error: Master secret must be exactly ${this.config.keyLength} bytes.`);
    }
  }

  /**
   * Encrypts a sensitive string payload using AES-256-GCM.
   * Generates a unique Initialization Vector (IV) for every isolated field mutation.
   *
   * @param plaintext - The raw, sensitive data string (e.g., PHI user summaries, names).
   * @returns A secure string containing the initialization vector, auth tag, and ciphertext.
   */
  public encryptField(plaintext: string): string {
    if (!plaintext) return '';

    // Generate a fresh, unique 12-byte initialization vector for every execution step
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv(this.config.algorithm, this.masterKey, iv);

    let ciphertext = cipher.update(plaintext, 'utf8', 'hex');
    ciphertext += cipher.final('hex');

    // Extract the cryptographic authentication tag generated by the GCM mode
    const authTag = cipher.getAuthTag();

    // Serialize the payload securely using a robust delimiter model
    return `${iv.toString('hex')}:${authTag.toString('hex')}:${ciphertext}`;
  }

  /**
   * Decrypts a previously encrypted field string value.
   * Validates payload integrity through GCM authentication tag verification.
   *
   * @param encryptedData - The serialized initialization vector, auth tag, and ciphertext string.
   * @returns The unredacted plaintext string.
   */
  public decryptField(encryptedData: string): string {
    if (!encryptedData) return '';

    const parts = encryptedData.split(':');
    if (parts.length !== 3) {
      throw new Error('Compliance Cryptographic Error: Malformed encryption token payload structure.');
    }

    const [ivHex, authTagHex, ciphertextHex] = parts;

    const iv = Buffer.from(ivHex, 'hex');
    const authTag = Buffer.from(authTagHex, 'hex');

    const decipher = crypto.createDecipheriv(this.config.algorithm, this.masterKey, iv);
    decipher.setAuthTag(authTag);

    let plaintext = decipher.update(ciphertextHex, 'hex', 'utf8');
    plaintext += decipher.final('utf8');

    return plaintext;
  }
}
